# Generated by Django 4.2 on 2023-05-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_tweetimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
